[package]
name = "ECE-522-Project-1"
version = "0.1.0"
edition = "2021"

[dependencies]
yahoo_finance_api = "2.3.0"
tokio = { version = "1.41.0", features = ["full"] }
clap = { version = "4.5.19", features = ["derive"] }
plotters = "0.3.7"
time = { version = "0.3.36", features = ["formatting"] }
